version: "3.8"
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: always
    volumes:
      - type: bind
        source: ./deconz
        target: /root/.local/share/dresden-elektronik/deCONZ
      - type: bind
        source: ./deconz-otau
        target: /root/otau
    devices:
       - /dev/ttyACM0
    ports:
      - 8080:8080
      - 8443:8443
      - 5900:5900
    environment:
      DECONZ_WEB_PORT: 8080
      DECONZ_WS_PORT: 8443
      DEBUG_INFO: 0
      DEBUG_APS: 0
      DEBUG_ZCL: 0
      DEBUG_ZDP: 0
      DEBUG_OTAU: 0
      TZ: Europe/Stockholm
      DECONZ_VNC_MODE: 1
      DECONZ_VNC_PORT: 5900
      DECONZ_VNC_PASSWORD: changeme
      DECONZ_UPNP: 0

  hass:
    image: homeassistant/raspberrypi4-homeassistant:stable
    container_name: hass
    restart: always
    network_mode: host
    volumes:
      - type: bind
        source: ./hass
        target: /config
    environment:
      TZ: Europe/Stockholm

  appdaemon:
    build: appdaemon-git
    container_name: appdaemon
    restart: always
    volumes:
      - type: bind
        source: ./appdaemon
        target: /conf
    ports:
      - 5050:5050
    env_file:
      - ./appdaemon.env
    environment:
      HA_URL: http://rpi-home:8123
      DASH_URL: http://rpi-home:5050
