version: "3.8"
services:
  hass:
    # linux/arm64 version
    image: homeassistant/home-assistant:2023.9.1@sha256:f74e9068b751cb7795eccd19b88de16fbd197bcd0f56695974ec1b73d384cf5b
    container_name: hass
    restart: always
    network_mode: host
    volumes:
      - type: bind
        source: ./containers/hass/config
        target: /config
    devices:
       - /dev/ttyACM0
    environment:
      TZ: Europe/Stockholm

  appdaemon:
    image: acockburn/appdaemon:4.4.2@sha256:7ca1ba3ead7c3c09ad7166c74a792340b436fe720512e19a2a4b1e0e7de928fe
    container_name: appdaemon
    restart: always
    volumes:
      - type: bind
        source: ./containers/appdaemon/config
        target: /conf
    ports:
      - 5050:5050
    env_file:
      - ./containers/appdaemon/appdaemon.env
    #command: -D DEBUG
