version: "3.8"
services:
  hass:
    image: homeassistant/raspberrypi4-64-homeassistant:2023.6.3@sha256:e195ff933ac023618f8448a13479a9a4f654e338e8b4a2d85e93863ca34c4d4f
    container_name: hass
    restart: always
    network_mode: host
    volumes:
      - type: bind
        source: ./containers/hass/config
        target: /config
    devices:
       - /dev/ttyACM0
    environment:
      TZ: Europe/Stockholm

  appdaemon:
    image: acockburn/appdaemon:4.2.3@sha256:61d11e634e351d6c3a5eb0fe25999294918e2613f87c96e06ee893b863bb23d5
    container_name: appdaemon
    restart: always
    volumes:
      - type: bind
        source: ./containers/appdaemon/config
        target: /conf
    ports:
      - 5050:5050
    env_file:
      - ./containers/appdaemon/appdaemon.env
    #command: -D DEBUG
