version: "3.8"
services:
  hass:
    image: homeassistant/raspberrypi4-64-homeassistant:2021.6.5
    container_name: hass
    restart: always
    network_mode: host
    volumes:
      - type: bind
        source: ./containers/hass/config
        target: /config
    devices:
       - /dev/ttyACM0
    environment:
      TZ: Europe/Stockholm

  appdaemon:
    build: containers/appdaemon/appdaemon-git
    container_name: appdaemon
    restart: always
    volumes:
      - type: bind
        source: ./containers/appdaemon/config
        target: /conf
    ports:
      - 5050:5050
    env_file:
      - ./containers/appdaemon/appdaemon.env
    environment:
      HA_URL: http://rpi-home:8123
      DASH_URL: http://rpi-home:5050
