version: "3.8"
services:
  hass:
    image: homeassistant/raspberrypi4-64-homeassistant:2023.6.3@sha256:e195ff933ac023618f8448a13479a9a4f654e338e8b4a2d85e93863ca34c4d4f
    container_name: hass
    restart: always
    network_mode: host
    volumes:
      - type: bind
        source: ./containers/hass/config
        target: /config
    devices:
       - /dev/ttyACM0
    environment:
      TZ: Europe/Stockholm

  appdaemon:
    image: acockburn/appdaemon:4.4.2@sha256:7ca1ba3ead7c3c09ad7166c74a792340b436fe720512e19a2a4b1e0e7de928fe
    container_name: appdaemon
    restart: always
    volumes:
      - type: bind
        source: ./containers/appdaemon/config
        target: /conf
    ports:
      - 5050:5050
    env_file:
      - ./containers/appdaemon/appdaemon.env
    #command: -D DEBUG
