services:
  hass:
    # linux/arm64 version
    image: homeassistant/home-assistant:2024.5.5@sha256:f90a02ddf24a6ccaf88305e2ccf171108525dacadf14b18fbe9ed90880e361e8
    container_name: hass
    restart: always
    network_mode: host
    volumes:
      - type: bind
        source: ./containers/hass/config
        target: /config
    devices:
       - /dev/ttyUSB0
    environment:
      TZ: Europe/Stockholm

  appdaemon:
    image: acockburn/appdaemon:4.4.2@sha256:7ca1ba3ead7c3c09ad7166c74a792340b436fe720512e19a2a4b1e0e7de928fe
    container_name: appdaemon
    restart: always
    volumes:
      - type: bind
        source: ./containers/appdaemon/config
        target: /conf
    ports:
      - 5050:5050
    env_file:
      - ./containers/appdaemon/appdaemon.env
    #command: -D DEBUG
